quarkus.log.category."net.mcbjd".level=DEBUG
#%dev.quarkus.log.level=DEBUG
quarkus.http.test-port=8888
quarkus.http.port=8081
quarkus.rest-client.skin-check.url=https://g79mclobt.nie.netease.com/pe/web/skin-md5-valid-inner
quarkus.rest-client.skin-check.scope=javax.inject.Singleton
quarkus.cache.caffeine."playerSkin".expire-after-access=1H
quarkus.cache.caffeine."playerSkin".maximum-size=5000
quarkus.cache.caffeine."playerSkin".initial-capacity=2000
quarkus.cache.caffeine."skinCache".expire-after-access=1H
quarkus.cache.caffeine."skinCache".maximum-size=5000
quarkus.cache.caffeine."skinCache".initial-capacity=1000
quarkus.vertx.warning-exception-time=10

quarkus.package.type=uber-jar

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.reactive.url=mysql://192.168.1.156:3306/minecraft
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

%dev.quarkus.http.port=8081
%test.quarkus.http.port=8083
%test.quarkus.rest-client.skin-check.url=https://g79mclexpr1.nie.netease.com/pe/web/skin-md5-valid-inner
%dev.quarkus.rest-client.skin-check.url=https://g79mclexpr1.nie.netease.com/pe/web/skin-md5-valid-inner
